#FROM node:latest
FROM mysql:5.7.28

EXPOSE 3306

COPY . /opt/code

WORKDIR /opt/code

#RUN /bin/bash -c 'chmod a+rx /opt/code/run.sh'
#RUN apt-get update
#RUN apt-get install -y mysql-server
#RUN /bin/bash -c 'npm i'
#RUN /bin/bash -c 'service mysql start && mysqladmin -u root password P2smo1G92Jc3H9H8 && mysqladmin -u root flush-privileges'
#RUN /bin/bash -c 'service mysql start && mysql -u root < loginService.sql'
#RUN /bin/bash -c 'service mysql start && mysql -u root < pickup.sql'

#ENTRYPOINT ["/opt/code/run.sh"]
